### ISSUE TITLE
Undefined names in pre_process.py

### ISSUE THREAD

**Issue by cclauss** [msgi/nlp-journey#4]
[flake8](http://flake8.pycqa.org) testing of https://github.com/msgi/nlp-journey on Python 3.7.1

$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./nlp/utils/pre_process.py:7:56: F821 undefined name 'stop_words'
    sentences = [' '.join([l for l in line if l not in stop_words]) for line in lines]
                                                       ^
./nlp/utils/pre_process.py:7:81: F821 undefined name 'lines'
    sentences = [' '.join([l for l in line if l not in stop_words]) for line in lines]
                                                                                ^
./nlp/utils/pre_process.py:10:22: F821 undefined name 'lines'
        o.writelines(lines)
                     ^
3     F821 undefined name 'stop_words'
3
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. These 5 are different from most other flake8 issues which are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

**Comment by msgi** [comment]
Thanks!
